config/routes.rb
Rails.application.routes.draw do
  resources :activities
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_drafts
  has_paper_trail on: [:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_paper_trail_whodunnit
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :reify_activity, only: :edit

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save_draft
        @activity.draft.publish! if params['commit'] == 'Publish'
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    @activity.assign_attributes(activity_params)
    respond_to do |format|
      if @activity.save_draft
        @activity.draft.publish! if params['commit'] == 'Publish'
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    #  Perhaps we can use one of the Callbacks ?
    @activity.draft? ? @activity.destroy : @activity.draft_destruction
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end
    # If the widget has a draft, load that version of it.
    def reify_activity
      @activity = @activity.draft.reify if @activity.draft?
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="color: red;">
    <%= @activity.draft? ? "Draft (Requesting #{@activity.draft.destroy? ? 'Destroy' : 'Publish'})" : 'Published'  %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <% if @activity.draft? && @activity.draft.destroy? %>
    <div>
      <p>Trashed</p>
      <%= link_to 'Destroy', @activity, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% else %>
    <div class="actions">
      <%= form.submit 'Publish' %>
      <%= form.submit 'Draft' %>
    </div>
  <% end %>

  <%# if @activity.draft? %>
    <%# if @activity.draft.destroy? %>
<!--      <div>-->
<!--        <p>Trashed</p>-->
        <%#= link_to 'Destroy', @activity, method: :delete, data: { confirm: 'Are you sure?' } %>
<!--      </div>-->
    <%# else %>
<!--      <div class="actions">-->
        <%#= form.submit 'Publish' %>
        <%#= form.submit 'Draft' %>
<!--      </div>-->
    <%# end %>
  <%# else %>
<!--    <div class="actions">-->
      <%#= form.submit 'Publish' %>
      <%#= form.submit 'Draft' %>
<!--    </div>-->
  <%# end %>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.description %></td>
        <td style="color: red;">
          <%= 'Published' if activity.published? && !activity.draft? %>
          <%= 'Draft' if activity.draft?  && !activity.published? %>
          <%= 'Published (with Draft)' if activity.published? && activity.draft? %>
        </td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: "#{activity.draft? ? 'Are you sure ? All drafts will be deleted too.' : 'Are you sure?'}" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= 'Published' if @activity.published? && !@activity.draft? %>
  <%= 'Draft' if @activity.draft?  && !@activity.published? %>
  <%= 'Published (with Draft)' if @activity.published? && @activity.draft? %>
</p>
<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drafty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>